### ISSUE TITLE
Functionality and how to run?

### ISSUE THREAD

**Issue by lendenis** [TaeHagen/rustpush#3]
Hello @TaeHagen 

I came across your project, its looks interesting.

Could you please share some more information how to run and use?

Thanks

**Comment by TaeHagen** [comment]
Currently this project is mainly a rust library designed to be integrated into other projects - there is no UI that allows you to easily use/run it, however projects based on this are in the works. You can look in src/test.rs for example code, run that with `cargo run`. If you'd like to add a basic TUI, contributions are welcome.

**Comment by TaeHagen** [comment]
There are currently some hoops in running this, mainly generating validation data. If you're unsure how, you can find me in the [pypush discord server](https://discord.gg/3mUWanWSEk) and I'd be happy to explain how to get you up and running. Hopefully soon that won't be required anymore, but for now it is.

**Comment by elminson** [comment]
How do I get the validation data?
in python we have `generate_validation_data` when we need to register a new user but the rust dont have it 
info!("Registering new identity...");
        print!("Enter validation data: ");

**Comment by TaeHagen** [comment]
Yeah, you get it from python at the moment. That is a work in progress, may change soon.
